# Generated by scripts/release.sh for v0.4.0. Do not edit by hand.
cask "duofx" do
  version "0.4.0"
  sha256 "03eeba8a5fbdc3a3398dacd7f3a13749fe9a795ce01c99b6248f5146fb2b25b0"

  url "https://github.com/amjadjibon/DuoFX/releases/download/v#{version}/DuoFX-v#{version}-arm64.dmg"
  name "DuoFX"
  desc "Menu-bar app that animates the desktop as the MacBook lid closes"
  homepage "https://duofx.amjadjibon.com/"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on macos: :sonoma

  app "DuoFX.app"

  uninstall quit: "com.amjadjibon.duofx"

  zap trash: [
    "~/Library/Preferences/com.amjadjibon.duofx.plist",
    "~/Library/Saved Application State/com.amjadjibon.duofx.savedState",
  ]
end
