# Generated by scripts/release.sh for v0.3.0. Do not edit by hand.
cask "duofx" do
  version "0.3.0"
  sha256 "11fde845da94fcd6252f65676bb61a95ab45a6d4fa9ffd84aeda1985c61ccd78"

  url "https://github.com/amjadjibon/DuoFX/releases/download/v#{version}/DuoFX-v#{version}-arm64.dmg",
      verified: "github.com/amjadjibon/DuoFX/"
  name "DuoFX"
  desc "Menu-bar app that animates the desktop as the MacBook lid closes"
  homepage "https://duofx.amjadjibon.com/"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on macos: :sonoma

  app "DuoFX.app"

  uninstall quit: "com.amjadjibon.duofx"

  zap trash: [
    "~/Library/Preferences/com.amjadjibon.duofx.plist",
    "~/Library/Saved Application State/com.amjadjibon.duofx.savedState",
  ]
end
