# Generated by scripts/release.sh for v0.0.3. Do not edit by hand.
cask "tokenbar" do
  version "0.0.3"
  sha256 "b6e4c3b3bda0d99e74c5b23258d5da94f0849d14a623af534a6540ebcf3a001a"

  url "https://github.com/amjadjibon/TokenBar/releases/download/v#{version}/TokenBar-#{version}.dmg"
  name "TokenBar"
  desc "Menu bar app for AI subscription quota usage"
  homepage "https://github.com/amjadjibon/TokenBar"

  depends_on macos: :tahoe

  app "TokenBar.app"

  uninstall quit: "com.amjadjibon.TokenBar"

  zap trash: [
    "~/Library/Application Support/TokenBar",
    "~/Library/Preferences/com.amjadjibon.TokenBar.plist",
  ]

  caveats <<~EOS
    Requires macOS 26.5 or later.
    This prerelease is not notarized. After installation, run:
      xattr -dr com.apple.quarantine /Applications/TokenBar.app
  EOS
end
