# Generated by scripts/release.sh for v0.0.5. Do not edit by hand.
cask "tokenbar" do
  version "0.0.5"
  sha256 "a965091fbcfba3b6dce39b43f0e42561bd8207b8bae8ec11883e759c9e4689a9"

  url "https://github.com/amjadjibon/TokenBar/releases/download/v#{version}/TokenBar-#{version}.dmg"
  name "TokenBar"
  desc "Menu bar app for AI subscription quota usage"
  homepage "https://github.com/amjadjibon/TokenBar"

  depends_on macos: :tahoe

  app "TokenBar.app"

  uninstall quit: "com.amjadjibon.TokenBar"

  zap trash: [
    "~/Library/Application Support/TokenBar",
    "~/Library/Preferences/com.amjadjibon.TokenBar.plist",
  ]

  caveats <<~EOS
    Requires macOS 26.5 or later.
    This prerelease is not notarized. After installation, run:
      xattr -dr com.apple.quarantine /Applications/TokenBar.app
  EOS
end
