# Generated by scripts/release.sh for v0.5.0. Do not edit by hand.
class Snaptext < Formula
  desc "Local OCR: read text from images, the clipboard, or the screen"
  homepage "https://github.com/amjadjibon/snaptext"
  url "https://github.com/amjadjibon/snaptext/releases/download/v0.5.0/snaptext-darwin-universal.tar.gz"
  # Stated explicitly: brew cannot read a version out of this filename.
  version "0.5.0"
  sha256 "38310102a7e0c60141708d8be58af670924a567d9a80872f67a91c96ce6f8790"
  license "MIT"

  depends_on macos: :sonoma

  def install
    bin.install "snaptext"
  end

  test do
    assert_match "snaptext #{version}", shell_output("#{bin}/snaptext --version")
  end
end
