# Generated by scripts/release.sh for v0.6.0. Do not edit by hand.
class Snaptext < Formula
  desc "Local OCR: read text from images, the clipboard, or the screen"
  homepage "https://github.com/amjadjibon/snaptext"
  url "https://github.com/amjadjibon/snaptext/releases/download/v0.6.0/snaptext-darwin-universal.tar.gz"
  # Stated explicitly: brew cannot read a version out of this filename.
  version "0.6.0"
  sha256 "79e6a32eebf973b34e1f569ebddc1c7283a04059ad3ecf814ebdbe96181a070f"
  license "MIT"

  depends_on macos: :sonoma

  def install
    bin.install "snaptext"
  end

  test do
    assert_match "snaptext #{version}", shell_output("#{bin}/snaptext --version")
  end
end
