# Generated by snaptext's scripts/release.sh for v0.4.0. Do not edit by hand.
class Snaptext < Formula
  desc "Local OCR: read text from images, the clipboard, or the screen"
  homepage "https://github.com/amjadjibon/snaptext"
  url "https://github.com/amjadjibon/snaptext/releases/download/v0.4.0/snaptext-darwin-universal.tar.gz"
  # Stated explicitly: brew cannot read a version out of this filename.
  version "0.4.0"
  sha256 "1bb9f708f9d587c7c0b6a0f8550b876541b88ca0aa114d3e76ecffbb9213ed5e"
  license "MIT"

  depends_on macos: :sonoma

  def install
    bin.install "snaptext"
  end

  test do
    assert_match "snaptext #{version}", shell_output("#{bin}/snaptext --version")
  end
end
